# Copyright 2020 Pants project contributors.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# See https://pants.readme.io/docs/using-pants-in-ci.

[GLOBAL]
dynamic_ui = false
pantsd = false

# Limit the maximum number of concurrent processes.
process_execution_local_parallelism = 4

[python-setup]
# Limit the maximum number of concurrent jobs used to resolve third party dependencies.
resolver_jobs = 1
